name: BuildJS
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install node
      uses: actions/setup-node@v1
      with:
          node-version: '12.x'

    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Install yarn
      run: npm install -g yarn

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn run build

    - name: Test
      run: yarn run test